window.LEARNING_COPY = {
  en: {
    title: 'A little English, just for you.', subtitle: 'Follow your curiosity. Take one expression with you.', discover: 'For you', review: 'Review', preferences: 'Tune my feed', progress: 'My progress',
    topics: ['Everyday life', 'Food & coffee', 'Life at work', 'Sounds & words', 'Stories & culture'], levels: ['Just starting', 'I know some basics', 'A little challenge'],
    prefTitle: 'Make this little corner yours.', prefLead: 'A starting point is enough. Change it whenever you like.', levelLabel: 'Where are you starting?', topicLabel: 'What catches your interest?', goalLabel: 'A small daily goal', goalUnit: 'new expressions', supportLabel: 'Video explanation', supportOptions: ['A mix is fine', 'English only first', 'Arabic explanations first'], savePrefs: 'Find my videos', skip: 'Just let me explore', close: 'Close', storage: 'Saved in this browser. No account needed.', storageError: 'This browser cannot save progress. You can still practice in this visit.',
    picked: 'Matches your interests', stretch: 'A small stretch', explore: 'Something to explore', due: 'Time to revisit', progressTitle: 'Little things you recognize', today: 'new expressions today', recognized: 'recognized so far', saved: 'saved for later', goalDone: 'Your little win for today. Keep going if you feel like it.', emptyProgress: 'Your first expression is waiting. Try a quick check on any video.', words: 'Your expression shelf', moreWords: 'Open my review', nothing: 'Your shelf starts here.', reviewEmpty: 'A little space for the things worth remembering.', reviewLead: 'Save an expression or try a quick check. Saved phrases, mistakes, and expressions due for another look appear here.', back: 'Find a video', allReviewed: 'You’ve reached the end of this little collection.', again: 'Explore again', reviewDone: 'All caught up for now.',
    english: 'English', arabicAudio: 'Arabic explanation', englishAudio: 'English audio', watch: 'Watch', play: 'Play', pause: 'Pause', sound: 'Sound on', mute: 'Muted', speed: 'Speed', next: 'Next video', previous: 'Previous video', save: 'Save expression', savedButton: 'Saved', like: 'More like this', less: 'Less like this', easy: 'Too easy', hard: 'Too hard', tuned: 'The next videos will follow your new pace.',
    quiz: 'Try a quick check', retry: 'Try again', checkTitle: 'What did you notice?', correct: 'You recognized it. A little win!', incorrect: 'Almost. Here’s the expression to take with you.', takeaway: 'Take this with you', example: 'Try saying it', meaning: 'Meaning', continue: 'Next little discovery', finish: 'Back to the feed', reviewLater: 'Saved. You can find it in Review.', noQuiz: 'Explore the expression below.',
    loading: 'Loading your video…', unavailable: 'This video isn’t playing right now.', unavailableLead: 'You can still practice the expression below, retry, or move to the next video.', reload: 'Retry video', number: 'of', notes: 'Expression notes', seeNotes: 'See the expression', hideNotes: 'Hide the notes', recNote: 'Your interests and recent first answers shape the next videos.', courseTitle: 'In the mood for more structure?', courseLead: 'Explore Chinese courses, a separate path alongside English video practice.', course: 'Explore courses', dailyWin: 'Small win, real progress', streak: 'day streak', all: 'All saved & due'
  },
  zh: {
    title: '为你准备的一点英语。', subtitle: '跟着兴趣刷，带走一个表达。', discover: '为你推荐', review: '再认一遍', preferences: '调整我的推荐', progress: '我的收获',
    topics: ['日常生活', '美食与咖啡', '工作那些事', '声音与词语', '故事与文化'], levels: ['刚刚开始', '已经懂一点', '想挑战一下'],
    prefTitle: '让这里，更像你的兴趣角落。', prefLead: '选一个起点就好，随时可以调整。', levelLabel: '你现在的起点是？', topicLabel: '什么会让你想多看一眼？', goalLabel: '每天一个小目标', goalUnit: '个新表达', supportLabel: '视频讲解偏好', supportOptions: ['都可以', '优先纯英语', '优先阿拉伯语讲解'], savePrefs: '找到我的视频', skip: '先随便逛逛', close: '关闭', storage: '进度保存在当前浏览器，无需注册。', storageError: '当前浏览器无法保存进度，这次访问中仍可继续练习。',
    picked: '符合你的兴趣', stretch: '小小挑战一下', explore: '换个角度看看', due: '到了复习时间', progressTitle: '你已经认出的那些小表达', today: '个新表达，今天认出来了', recognized: '个表达已认出', saved: '个表达已收藏', goalDone: '今天的小目标达成了。有兴趣的话，可以再刷一条。', emptyProgress: '你的第一个表达正在等你。试试任意视频的小测。', words: '我的表达收藏架', moreWords: '打开复习', nothing: '你的收藏架，从这里开始。', reviewEmpty: '把值得记住的，留一个位置。', reviewLead: '收藏表达，或者试一道小题。收藏、错题和到期的表达都会出现在这里。', back: '找条视频看看', allReviewed: '这一小组，已经看到最后了。', again: '再逛一遍', reviewDone: '这轮复习完成了。',
    english: '英语', arabicAudio: '阿拉伯语讲解', englishAudio: '英语原声', watch: '看视频', play: '播放', pause: '暂停', sound: '声音开启', mute: '静音', speed: '语速', next: '下一条视频', previous: '上一条视频', save: '收藏表达', savedButton: '已收藏', like: '多推荐这类', less: '少推荐这条', easy: '太简单', hard: '有点难', tuned: '接下来的视频会按新的节奏推荐。',
    quiz: '试一道小题', retry: '再试一次', checkTitle: '刚才，你注意到了什么？', correct: '你认出来了，又多懂了一点！', incorrect: '差一点。看看这次可以带走的表达。', takeaway: '这次，可以带走', example: '试着说一句', meaning: '意思是', continue: '继续发现下一条', finish: '返回视频', reviewLater: '已收藏，可以去“再认一遍”里找到它。', noQuiz: '看看下面的表达。',
    loading: '视频加载中…', unavailable: '这条视频暂时无法播放。', unavailableLead: '可以先练下面的表达，也可以重试或看下一条。', reload: '重新播放', number: '/', notes: '表达笔记', seeNotes: '看看这个表达', hideNotes: '收起笔记', recNote: '你的兴趣和最近几次首次作答，会影响下一批视频。', courseTitle: '想把基础串起来？', courseLead: '还有创始人讲授的中文课程，可作为英语视频练习之外的另一条学习路径。', course: '探索课程', dailyWin: '小小一步，真有收获', streak: '天连续练习', all: '收藏与待复习'
  },
  ar: {
    title: 'قليل من الإنجليزية، لك أنت.', subtitle: 'اتبع فضولك وخذ معك تعبيراً واحداً.', discover: 'لك', review: 'المراجعة', preferences: 'ضبط مقاطعي', progress: 'تقدمي',
    topics: ['الحياة اليومية', 'الطعام والقهوة', 'الحياة في العمل', 'الأصوات والكلمات', 'قصص وثقافة'], levels: ['أبدأ الآن', 'أعرف بعض الأساسيات', 'أريد تحدياً صغيراً'],
    prefTitle: 'اجعل هذه الزاوية الصغيرة لك.', prefLead: 'نقطة بداية تكفي. غيّرها متى شئت.', levelLabel: 'من أين تبدأ؟', topicLabel: 'ما الذي يثير اهتمامك؟', goalLabel: 'هدف يومي صغير', goalUnit: 'تعبيرات جديدة', supportLabel: 'شرح الفيديو', supportOptions: ['مزيج مناسب', 'الإنجليزية أولاً', 'الشرح بالعربية أولاً'], savePrefs: 'اعثر على مقاطعي', skip: 'دعني أستكشف أولاً', close: 'إغلاق', storage: 'يُحفظ التقدم في هذا المتصفح دون حساب.', storageError: 'لا يمكن حفظ التقدم في هذا المتصفح. يمكنك متابعة التدريب خلال هذه الزيارة.',
    picked: 'يناسب اهتماماتك', stretch: 'تحدٍ صغير', explore: 'شيء جديد للاستكشاف', due: 'حان وقت المراجعة', progressTitle: 'تعبيرات صغيرة تعرفت عليها', today: 'تعبيرات جديدة اليوم', recognized: 'تعبيرات تعرفت عليها', saved: 'محفوظة لوقت لاحق', goalDone: 'حققت هدفك الصغير اليوم. تابع إذا أحببت.', emptyProgress: 'تعبيرك الأول ينتظرك. جرّب سؤالاً مع أي مقطع.', words: 'رف تعبيراتك', moreWords: 'افتح المراجعة', nothing: 'رفك يبدأ هنا.', reviewEmpty: 'مساحة صغيرة لما يستحق التذكر.', reviewLead: 'احفظ تعبيراً أو أجب عن سؤال. تظهر هنا المحفوظات والأخطاء والتعبيرات التي حان وقت مراجعتها.', back: 'اعثر على مقطع', allReviewed: 'وصلت إلى نهاية هذه المجموعة الصغيرة.', again: 'استكشف مجدداً', reviewDone: 'انتهيت من المراجعة الآن.',
    english: 'الإنجليزية', arabicAudio: 'شرح عربي', englishAudio: 'صوت إنجليزي', watch: 'شاهد', play: 'تشغيل', pause: 'إيقاف مؤقت', sound: 'الصوت يعمل', mute: 'صامت', speed: 'السرعة', next: 'المقطع التالي', previous: 'المقطع السابق', save: 'احفظ التعبير', savedButton: 'محفوظ', like: 'المزيد مثل هذا', less: 'أقل مثل هذا', easy: 'سهل جداً', hard: 'صعب قليلاً', tuned: 'ستتبع المقاطع القادمة إيقاعك الجديد.',
    quiz: 'جرّب سؤالاً سريعاً', retry: 'حاول مجدداً', checkTitle: 'ماذا لاحظت؟', correct: 'تعرفت عليه. إنجاز صغير!', incorrect: 'اقتربت. إليك التعبير الذي يمكنك أخذه معك.', takeaway: 'خذ هذا معك', example: 'حاول أن تقول', meaning: 'المعنى', continue: 'إلى الاكتشاف التالي', finish: 'العودة إلى المقاطع', reviewLater: 'تم الحفظ. ستجده في المراجعة.', noQuiz: 'استكشف التعبير أدناه.',
    loading: 'جارٍ تحميل الفيديو…', unavailable: 'لا يعمل هذا الفيديو حالياً.', unavailableLead: 'يمكنك التدرب على التعبير أدناه أو إعادة المحاولة أو الانتقال للتالي.', reload: 'أعد المحاولة', number: 'من', notes: 'ملاحظات التعبير', seeNotes: 'شاهد التعبير', hideNotes: 'أخفِ الملاحظات', recNote: 'تساعد اهتماماتك وإجاباتك الأولى الأخيرة في اختيار المقاطع التالية.', courseTitle: 'ترغب في تعلّم أكثر تنظيماً؟', courseLead: 'استكشف دورات الصينية، مساراً منفصلاً إلى جانب تدريب الإنجليزية بالمقاطع.', course: 'استكشف الدورات', dailyWin: 'إنجاز صغير وتقدم حقيقي', streak: 'أيام تدريب متتالية', all: 'المحفوظات والمراجعات'
  }
};
